# Generated by Django 6.0.6 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_shopuser_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(default='ashkanbyo@gmail.com', max_length=254),
        ),
    ]
