# Generated by Django 6.0.6 on 2026-07-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productfeature_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
